### PR TITLE
Issue: Extract Exploration Component Completed. 

### PR DESCRIPTION
**Pull request by cloudthepain**
Works the same as challenges.

Added the ASCII Exploration into the Explore Folder.

### CODE REVIEW

**Review by jcollard — CHANGES_REQUESTED** [review]
Cool! Some general notes to finish:

* Don't name files with `_` in them. Instead, put `Explore` at the end. I would actually prefer if the `Explore` component were renamed `Exploration` and all files were appended with `Exploration`. For example, `DisplayingADoubleQuoteExploratioin.razor`

* Also, your branch has a bunch of errors since you moved the `Explore.razor` file without updating the `_imports.razor` file to reference it.

* You should move all of the files that use `Explore` component into the `Explore` package.

**Comment by cloudthepain** [comment]
@jcollard 

Requested Adjustments Made.

**Comment by cloudthepain** [comment]
@jcollard 

Merged and Addressed Conflicts.
    The information that you changed for the Exploration (bolding, wording, ect.) was transferred over to my version in the appropriate exploration file.

**Review by jcollard — APPROVED** [review]
Great work! Squash and merge when you're ready to deploy to develop 👍

**Pull request merged**
